apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: atabiti-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atabiti-app
  template:
    metadata:
      labels:
        app: atabiti-app
    spec:
      containers:
      - name: atabiti-app
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: atabiti-service
spec:
  selector:
    name: atabiti-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
