apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: atabiti-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atabiti-app
  template:
    metadata:
      labels:
        app: atabiti-app
    spec:
      containers:
      - name: atabiti-app
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---

apiVersion: v1
kind: Service
metadata:
  name: atabiti-service
  namespace: dev
# spec:
#   selector:
#     app: atabiti-app
#   ports:
#     - protocol: TCP
#       port: 8888
#       targetPort: 8888
#       nodePort: 30080
#   type: NodePort
spec:
  selector:
    app: atabiti-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30081  
  - name: https
    port: 443
    targetPort: 8080
    nodePort: 30082

# apiVersion: v1
# kind: Service
# metadata:
#   name: atabiti-service
# spec:
#   selector:
#     app: atabiti-app
#   ports:
#     - protocol: TCP
#       port: 8888
#       targetPort: 8888
#       nodePort: 32767
#   type: NodePort
